// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrojijxeggmyivzovkjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyb2ppanhlZ2dteWl2em92a2pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5OTkzMzksImV4cCI6MjA1ODU3NTMzOX0.xvs-rQow79646MOPuUttyMvyeT4dpGUYTuLpJSJL6Uc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);